In [1]:
# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
'''
purpose of numpy is for faster calculation better computation of homogeneus data type.
advantages are when large number of data needs to be processed we use numpy array
*matrics, *ndimentions are calculated faster saving time and its memory capacity
It enhances python's capabilites for numerical operations because of its built is based on c programming which makes its compution faster.
'''

"\npurpose of numpy is for faster calculation better computation of homogeneus data type.\nadvantages are when large number of data needs to be processed we use numpy array\n*matrics, *ndimentions are calculated faster saving time and its memory capacity\nIt enhances python's capabilites for numerical operations because of its built is based on c programming which makes its compution faster.\n"

In [2]:
# Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
'''
np.mean() is used to calculate simple arimthmatic operations like adding all the values and divide whith n numbers
np.average() helps in calculating numbers or elements with weights or missing value
'''

'\nnp.mean() is used to calculate simple arimthmatic operations like adding all the values and divide whith n numbers\nnp.average() helps in calculating numbers or elements with weights or missing value\n'

In [3]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
'''
Reversing the array in numpy is by using flip() and axis is given to control row and column
'''
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.flip(arr), "\n")
arr1 = ([2, 3, 4],[1, 5, 6])
print(np.flip(arr1, axis = 0), "\n")
np.flip(arr1, axis = 1)



[4 3 2 1] 

[[1 5 6]
 [2 3 4]] 



array([[4, 3, 2],
       [6, 5, 1]])

In [4]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
'''
type is determined by passing the arguments in side type() function
data type is necessary for memory optimization and faster efficiency
'''
ty = np.flip(arr)
ty.dtype

dtype('int64')

In [5]:
# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
'''
ndarray is n dimentional array (eg: 2d, 3d, 4d) it much more faster than normal array list from python, contains only homogeneuos data type making it easy for computation
'''

'\nndarray is n dimentional array (eg: 2d, 3d, 4d) it much more faster than normal array list from python, contains only homogeneuos data type making it easy for computation\n'

In [6]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
'''
numpy array is contigues and opertaion performed on all once at a time which makes it super fast
'''


'\nnumpy array is contigues and opertaion performed on all once at a time which makes it super fast\n'

In [7]:
# 7.  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
'''
vstack for intergrating vertically where columns should be same
hsatck for intergrating horizontally where rows must be same
'''
a = [1, 2, 3, 4]
b = ([6, 7, 8, 9], [2, 3, 4, 5])
e = [5, 6, 7, 8]
c = np.hstack((a, e))
d = np.vstack((a, b))
print("hstack = ", c)
print("\nvstack = ", d)

hstack =  [1 2 3 4 5 6 7 8]

vstack =  [[1 2 3 4]
 [6 7 8 9]
 [2 3 4 5]]


In [8]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
'''
fliplr() is used for left to right flip
flipud() is used for up to down flip
'''
import numpy as np
a = np.array([[1, 2, 3, 4]])
c = np.array([[1, 2, 3, 4]])
b = np.array([[3, 4, 5], [6, 7, 8]])
print(np.flipud(a))
print(np.fliplr(a))
print(np.fliplr(b))
print(np.flipud(b))
print(np.fliplr(c))
print(np.flipud(c))

[[1 2 3 4]]
[[4 3 2 1]]
[[5 4 3]
 [8 7 6]]
[[6 7 8]
 [3 4 5]]
[[4 3 2 1]]
[[1 2 3 4]]


In [9]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
'''
array_split() method is used for spliting array into half
'''
arr = np.array([1, 2, 3, 4, 5])
np.array_split(arr, 2)



[array([1, 2, 3]), array([4, 5])]

In [10]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
'''
vectorization is iteraring through the array element wise
broadcasting is done when different dimentions are present
'''
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4])


result = a + b
print(result)

[5 6 7]


Practical Questions


In [11]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
a = np.random.randint(1, 100, (3,3))
print(a)
a.T

[[ 1 66 45]
 [58 63  8]
 [62  2 50]]


array([[ 1, 58, 62],
       [66, 63,  2],
       [45,  8, 50]])

In [12]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
a = np.arange(10)
print(a.reshape(2, 5))
print(a.reshape(5, 2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
arr = np.random.randint(1, 20, (4, 4))
np.zeros((6, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
arr = np.random.randint(1, 20, (4, 4))
np.pad(arr, 1)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  7,  6, 11,  4,  0],
       [ 0, 19, 19, 11, 17,  0],
       [ 0, 13, 13, 13,  1,  0],
       [ 0,  2, 11, 14,  7,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [15]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5
np.arange(10, 60, 5)


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [16]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
arr = np.array(['python', 'numpy', 'pandas'])
print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.title(arr))


['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [17]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
arr = np.array(['python', 'numpy', 'pandas'])
np.char.join(' ', arr)

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [18]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])
arr2 = np.array([3, 5, 7, 9, 1])
addition_arr = arr1 + arr2
print(f" addition of two array{addition_arr}")
sub_arr = arr1 - arr2
print(f"subtracting two arrays {sub_arr}")
mul_arr = arr1 * arr2
print(f"multiplication of two arrays {mul_arr}")

 addition of two array[[ 4  7 10 13  6]
 [ 9 12 15 18  1]]
subtracting two arrays [[-2 -3 -4 -5  4]
 [ 3  2  1  0 -1]]
multiplication of two arrays [[ 3 10 21 36  5]
 [18 35 56 81  0]]


In [19]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
arr = np.random.randint(1, 5, (5, 5))
print(f"diagonal of\n {arr} \nis {arr.diagonal()}")

diagonal of
 [[4 2 3 4 1]
 [2 4 4 3 2]
 [2 3 3 1 4]
 [2 4 4 1 3]
 [2 1 3 1 3]] 
is [4 4 3 1 3]


In [59]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

n = np.random.randint(0, 1000, (1, 100))
print(n)
prime_list = []
n = n.flatten()
for i in n:
  num = int(i)
  if num > 1:
    for j in range(2, num):
      if (num % j) == 0:
        break
    else:
      prime_list.append(num)
print(prime_list)


[[470 814 408 784  21 226  52 999  12 208 863 413 574 899 375 920 317 650
  788 765 320 411 931  50 852 304 381 218 883 225 500 816 370 328 559 655
  613 824 248  90 861 890 700 822 468  54 127 958  56 678 631 147 331 409
  793 745 261 113 321 802  82   4 922 422 758 411 580 374 331 607 556 693
  681 715  28 798 935  43 184  50 128 974 370 229 624 222 357 607 491  64
  948 553 367 986   7 866 681 850 310  82]]
[863, 317, 883, 613, 127, 631, 331, 409, 113, 331, 607, 43, 229, 607, 491, 367, 7]


n = int(input("Enter the number"))
i = 1
for n in range(1, 11):
  print(n , "x", i, "=", n*i)
  i=i+1


In [46]:
# 10.  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
daily_temp = np.random.randint(18, 25, (5, 7))
avg_temp = []
#for temp in daily_temp:
for i in range(1,5):
  a = np.mean(daily_temp[i])
  avg_temp.append(a)
print(f" {daily_temp} \naverage temperature per week is\n {avg_temp}")

 [[19 23 22 20 22 22 23]
 [21 18 20 22 21 21 22]
 [19 22 23 21 22 22 24]
 [19 20 23 18 19 24 18]
 [24 22 24 23 20 22 20]] 
average temperature per week is
 [20.714285714285715, 21.857142857142858, 20.142857142857142, 22.142857142857142]
